site_name: Gesso WordPress Theme
repo_url: https://github.com/forumone/gesso-wp/
site_author: Forum One
site_description: Gesso is a Sass-based starter theme that outputs accessible HTML5 markup. It uses a mobile-first responsive approach and leverages SMACSS for style organization. This encourages a component-based approach to theming through the creation of discrete, reusable UI elements.
theme: readthedocs
pages:
  - About: index.md